Document: unity-greeter-badges
Title: Debian unity-greeter-badges Manual
Author: <insert document author here>
Abstract: This manual describes what unity-greeter-badges is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/unity-greeter-badges/unity-greeter-badges.sgml.gz

Format: postscript
Files: /usr/share/doc/unity-greeter-badges/unity-greeter-badges.ps.gz

Format: text
Files: /usr/share/doc/unity-greeter-badges/unity-greeter-badges.text.gz

Format: HTML
Index: /usr/share/doc/unity-greeter-badges/html/index.html
Files: /usr/share/doc/unity-greeter-badges/html/*.html
